name: Push documentation to docs repo

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: '16'
      - name: Install dependencies
        run: |
          yarn install --ignore-engines  
          yarn run generate-doc
  push-to-docs:       
      uses: nevermined-io/reusable-workflows/.github/workflows/push-to-docs.yml@main
      with:
        path-to-push: external/cli
        repo-to-push: nvm-docs
      secrets: inherit
