name: Push documentation to docs repo

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  push-to-docs:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        yarn install --ignore-engines  
        yarn run generate-doc
    - uses: nevermined-io/reusable-workflows/.github/workflows/push-to-docs.yml@main
      with:
        path-to-push: external/cli
      secrets: inherit
