name: GitHub Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.API_TOKEN_GITHUB }}

      # Build process
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Update CHANGELOG.md
        id: changelog
        run: |
          npm install auto-changelog
          npx auto-changelog
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated CHANGELOG.md update
          commit_options: "--no-verify --signoff"
          file_pattern: CHANGELOG.md
          branch: main

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1