name: Tests Nightly

on:
  schedule:
    - cron: '30 3 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          yarn install --ignore-engines
      - name: Lint
        run: |
          yarn lint
      - name: Run e2e tests
        env:
          LOCAL_CONF_DIR: "/tmp/.nevermined"
          SEED_WORDS: ${{ secrets.MNEMONIC_TESTING_MUMBAI }}
          TOKEN_ADDRESS: "0x001B3B4d0F3714Ca98ba10F6042DaEbF0B1B7b6F"
          WEB3_PROVIDER_URL: https://polygon-mumbai.infura.io/v3/${{ secrets.INFURA_TOKEN }}
          NETWORK: "mumbai"
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
        run: |
          sleep 10
          yarn build
          yarn test test/integration-tests/NFTs1155.test.ts
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt
