name: Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--spree-embedded-contracts", "--polygon"]
        node: ["16"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          yarn install --ignore-engines
      - name: Lint
        run: |
          yarn lint
      - name: Reclaim some disk space
        run: |
          docker system prune --all --volumes -f
      - name: Run Nevermined Tools
        env:
          LOCAL_CONF_DIR: ${{secrets.LOCAL_CONF_DIR}}      
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools
          cd tools

          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"

          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"
          ./start_nevermined.sh ${{ matrix.network }} 2>&1 | tee nevermined_tools.txt &
          cd ..
          ./scripts/wait-nevermined.sh $LOCAL_CONF_DIR
          ./scripts/wait-subgraphs.sh

      - name: Run integration tests
        env:
          MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          TOKEN_ADDRESS: "0x0000000000000000000000000000000000000000"
          NODE_URL: "http://localhost:8545"
        run: |
          sleep 10
          yarn build
          yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt
